# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

extract_nonzero_slices_cpp <- function(array, dimensions, threshold = -1.0) {
    .Call(`_ramri_extract_nonzero_slices_cpp`, array, dimensions, threshold)
}

